version: '2'
services:
  tip:
    build:
      context: ./src
    environment:
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_SCHEMA: ${DB_SCHEMA}
      LOGS_FOLDER: ${TIP_LOGS_FOLDER}
      PORT: ${TIP_PORT}
      SSL_PATH: ${TIP_SSL_PATH}
      SSL_KEY: ${TIP_SSL_KEY}
      SSL_CERT: ${TIP_SSL_CERT}
      SSL_CA_CERT: ${TIP_SSL_CA_CERT}
      TOKEN_ISSUER: ${TIP_ISSUE_NAME}
      AUTH_REQUESTS: ${TIP_AUTH_REQUESTS}
      TEP_ADDRESS: ${TEP_ADDRESS}
      SEND_PUBLIC_KEY: ${TIP_SEND_PUBLIC_KEY}
      NUM_THREADS: ${TIP_NUM_THREADS}
      KEY_POOL_ENABLED: ${TIP_KEY_POOL_ENABLED}
      TIP_KEY_POOL_SIZE: ${TIP_KEY_POOL_SIZE}
    depends_on:
     - "tip-db"
    volumes:
      - ./logs:/logs
    ports:
      - 8445:443
  tip-db:
    image: postgres
    ports:
    - 6435:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
