version: '2'
services:
  tip:
    build:
      context: ./src
      args:
        TIP_PORT: ${TIP_PORT}
    environment:
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_SCHEMA: ${DB_SCHEMA}
      PORT: ${TIP_PORT}
    depends_on:
     - "tip-db"
    volumes:
      - ./logs:/log

  tip-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
